model:
  type: vit
  name: google/vit-base-patch16-224
  use_lora: false
  lora:
    r: 8
    lora_alpha: 32
    target_modules: ["query", "key", "value", "dense"]
    lora_dropout: 0.1
    bias: "none"

